### ISSUE TITLE
org.mule.tooling.client.api.exception.ToolingException: Couldn't create the class loader for the Tooling Client

### ISSUE THREAD

**Issue by javaduke** [mulesoft-labs/data-weave-intellij-plugin#20]
I just installed the latest dev snapshot of the plugin and created a new mule application. Then I saw this error:

org.mule.tooling.client.api.exception.ToolingException: Couldn't create the class loader for the Tooling Client
org.mule.maven.client.api.BundleDependenciesResolutionException: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.mule.tooling:mule-runtime-tooling-client:jar:4.1.3-20180725.134656-1 in mulesoft-snapshots (https://repository.mulesoft.org/snapshots/)
	at org.mule.maven.client.internal.AetherMavenClient.resolveBundleDescriptorDependencies(AetherMavenClient.java:221)
	at org.mule.tooling.client.bootstrap.internal.DefaultToolingRuntimeClientBootstrap.resolveDependency(DefaultToolingRuntimeClientBootstrap.java:235)
	at org.mule.tooling.client.bootstrap.internal.DefaultToolingRuntimeClientBootstrap.createClassLoader(DefaultToolingRuntimeClientBootstrap.java:163)
	at org.mule.tooling.client.bootstrap.internal.DefaultToolingRuntimeClientBootstrap.<init>(DefaultToolingRuntimeClientBootstrap.java:122)
	at org.mule.tooling.client.bootstrap.api.ToolingRuntimeClientBootstrapFactory.newToolingRuntimeClientBootstrap(ToolingRuntimeClientBootstrapFactory.java:28)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.lambda$createToolingClientBootstrap$0(ToolingRuntimeManager.java:134)
	at com.intellij.openapi.util.ClassLoaderUtil.runWithClassLoader(ClassLoaderUtil.java:42)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.createToolingClientBootstrap(ToolingRuntimeManager.java:134)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.initRuntimeClient(ToolingRuntimeManager.java:105)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.access$200(ToolingRuntimeManager.java:33)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager$1.run(ToolingRuntimeManager.java:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:728)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:404)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:316)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.mule.tooling:mule-runtime-tooling-client:jar:4.1.3-20180725.134656-1 in mulesoft-snapshots (https://repository.mulesoft.org/snapshots/)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.mule.maven.client.internal.AetherMavenClient.readArtifactDescriptor(AetherMavenClient.java:346)
	at org.mule.maven.client.internal.AetherMavenClient.resolveBundleDescriptorDependencies(AetherMavenClient.java:215)
	... 23 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.mule.tooling:mule-runtime-tooling-client:jar:4.1.3-20180725.134656-1 in mulesoft-snapshots (https://repository.mulesoft.org/snapshots/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 28 more

	at org.mule.tooling.client.bootstrap.internal.DefaultToolingRuntimeClientBootstrap.createClassLoader(DefaultToolingRuntimeClientBootstrap.java:198)
	at org.mule.tooling.client.bootstrap.internal.DefaultToolingRuntimeClientBootstrap.<init>(DefaultToolingRuntimeClientBootstrap.java:122)
	at org.mule.tooling.client.bootstrap.api.ToolingRuntimeClientBootstrapFactory.newToolingRuntimeClientBootstrap(ToolingRuntimeClientBootstrapFactory.java:28)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.lambda$createToolingClientBootstrap$0(ToolingRuntimeManager.java:134)
	at com.intellij.openapi.util.ClassLoaderUtil.runWithClassLoader(ClassLoaderUtil.java:42)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.createToolingClientBootstrap(ToolingRuntimeManager.java:134)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.initRuntimeClient(ToolingRuntimeManager.java:105)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager.access$200(ToolingRuntimeManager.java:33)
	at org.mule.tooling.runtime.tooling.ToolingRuntimeManager$1.run(ToolingRuntimeManager.java:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:728)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:404)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:316)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by machaval** [comment]
Thanks for the report we will take a look at it
