### ISSUE TITLE
Can not create new project

### ISSUE THREAD

**Issue by dyeeye** [mulesoft-labs/data-weave-intellij-plugin#26]
I use newest version of IntelliJ 2018.2.5 community edition. When I hit button Create New Project I receive an exception as follows:

`java.lang.NullPointerException
	at org.mule.tooling.runtime.sdk.MuleSdkManagerStoreImpl.findFromVersion(MuleSdkManagerStoreImpl.java:94)
	at org.mule.tooling.runtime.wizard.MuleVersionConfiguration.<init>(MuleVersionConfiguration.java:26)
	at org.mule.tooling.runtime.wizard.MuleAppModuleBuilder.getCustomOptionsStep(MuleAppModuleBuilder.java:135)
	at com.intellij.ide.projectWizard.ProjectTypeStep.showCustomOptions(ProjectTypeStep.java:457)
	at com.intellij.ide.projectWizard.ProjectTypeStep.projectTypeChanged(ProjectTypeStep.java:384)
	at com.intellij.ide.projectWizard.ProjectTypeStep$7.valueChanged(ProjectTypeStep.java:205)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2210)
	at javax.swing.JList.setSelectedValue(JList.java:2360)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:231)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:50)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:39)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:37)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:382)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:369)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:60)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:69)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:326)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Because of this I do not get form with project type to select. The error occur for last build Mule 4 Runtime. 2.0.4-20181102.213451

**Comment by javaduke** [comment]
The Mule version is extracted from the name of the directory which contains the mule distribution. Can you please provide the full path to your Mule Runtime installation? We may need to figure out a different way to detect the Runtime version...

**Comment by dyeeye** [comment]
I have installed runtime in completely different path than IntelliJ. Mule location is C:\Users\patry\Downloads\mule-standalone-4.1.1. In there a requirement to place Mule in some fixed place?
________________________________
Od: javaduke <notifications@github.com>
Wysłane: środa, 7 listopada 2018 15:05
Do: mulesoft-labs/data-weave-intellij-plugin
DW: Patryk; Author
Temat: Re: [mulesoft-labs/data-weave-intellij-plugin] Can not create new project (#26)


The Mule version is extracted from the name of the directory which contains the mule distribution. Can you please provide the full path to your Mule Runtime installation? We may need to figure out a different way to detect the Runtime version...

**Comment by javaduke** [comment]
> Mule location is C:\Users\patry\Downloads\mule-standalone-4.1.1.

Ah, yes, that explains it. Currently the way the plugin detects the version is parsing the directory name which is in the format of "mule-enterprise-standalone-X.X.X". I agree that this is unreliable and will work on a better version detection method. As a quick fix, you can download and install the latest Mule 4 Enterprise.

**Comment by dyeeye** [comment]
I can keep it anywhere I like? I did not mention it before but I have also a second one C:\Users\patry\Downloads\mule-ee-distribution-standalone-4.1.4\mule-enterprise-standalone-4.1.4
installed
