### ISSUE TITLE
Write access is allowed inside write-action only

### ISSUE THREAD

**Issue by chka73** [mulesoft-labs/data-weave-intellij-plugin#40]
MacOs
Plugin Version 2.0.21

```
java.lang.Throwable: Assertion failed: Write access is allowed inside write-action only (see com.intellij.openapi.application.Application.runWriteAction())
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteAccessAllowed(ApplicationImpl.java:1283)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvent(PersistentFSImpl.java:686)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.createChildDirectory(PersistentFSImpl.java:436)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.createChildDirectory(VirtualFileSystemEntry.java:283)
	at org.mule.tooling.lang.dw.service.WeaveRuntimeContextManager.getScenariosRootFolder(WeaveRuntimeContextManager.java:471)
	at org.mule.tooling.lang.dw.service.WeaveRuntimeContextManager.getScenariosRootFolder(WeaveRuntimeContextManager.java:438)
	at org.mule.tooling.lang.dw.service.WeaveRuntimeContextManager.findMappingTestFolder(WeaveRuntimeContextManager.java:376)
	at org.mule.tooling.lang.dw.service.WeaveRuntimeContextManager.findScenarios(WeaveRuntimeContextManager.java:364)
	at org.mule.tooling.lang.dw.service.WeaveRuntimeContextManager.getScenariosFor(WeaveRuntimeContextManager.java:357)
	at org.mule.tooling.lang.dw.service.WeaveRuntimeContextManager.getCurrentScenarioFor(WeaveRuntimeContextManager.java:318)
	at org.mule.tooling.lang.dw.service.WeaveRuntimeContextManager.getImplicitInputTypes(WeaveRuntimeContextManager.java:268)
	at org.mule.tooling.lang.dw.service.WeaveEditorToolingAPI.lambda$didOpen$1(WeaveEditorToolingAPI.java:186)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at org.mule.tooling.lang.dw.service.WeaveEditorToolingAPI.didOpen(WeaveEditorToolingAPI.java:172)
	at org.mule.tooling.lang.dw.service.WeaveEditorToolingAPI.resolveReference(WeaveEditorToolingAPI.java:219)
	at org.mule.tooling.lang.dw.reference.WeaveIdentifierPsiReference.resolveInner(WeaveIdentifierPsiReference.java:28)
	at org.mule.tooling.lang.dw.reference.WeaveIdentifierPsiReference$MyResolver.resolve(WeaveIdentifierPsiReference.java:51)
	at org.mule.tooling.lang.dw.reference.WeaveIdentifierPsiReference$MyResolver.resolve(WeaveIdentifierPsiReference.java:45)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:202)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:201)
	at org.mule.tooling.lang.dw.reference.WeaveIdentifierPsiReference.multiResolve(WeaveIdentifierPsiReference.java:42)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:385)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:363)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:235)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:207)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)```

**Comment by machaval** [comment]
Fixed
