### ISSUE TITLE
java.lang.NoSuchFieldError: Console_log

### ISSUE THREAD

**Issue by iponisio** [mulesoft-labs/data-weave-intellij-plugin#46]
Hi folks,

After moving to Intellij IDEA Ultimate 👇 

> IntelliJ IDEA 2020.1.1 (Ultimate Edition)
> Build #IU-201.7223.91, built on April 30, 2020
> 
> Runtime version: 11.0.6+8-b765.40 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.6
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1979M
> Cores: 12
> Non-Bundled Plugins: org.mule.tooling.intellij.dataweave.v2, aws.toolkit, org.intellij.scala

I started observing the following error in the event log:

```
java.lang.NoSuchFieldError: Console_log
	at org.mule.tooling.lang.dw.preview.WeavePreviewComponent.createPreviewPanel(WeavePreviewComponent.java:107)
	at org.mule.tooling.lang.dw.preview.WeavePreviewComponent.createComponent(WeavePreviewComponent.java:85)
	at org.mule.tooling.lang.dw.preview.PreviewToolWindowPanel.setupUI(PreviewToolWindowPanel.java:59)
	at org.mule.tooling.lang.dw.preview.PreviewToolWindowPanel.lambda$new$0(PreviewToolWindowPanel.java:53)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$8(DumbServiceImpl.java:623)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

This is preventing the weave preview from being displayed.

![image](https://user-images.githubusercontent.com/46690232/81450948-d632ed00-9159-11ea-84a3-3cd27c60b40d.png)

**Comment by iponisio** [comment]
Plugin version:
![image](https://user-images.githubusercontent.com/46690232/81451340-a9cba080-915a-11ea-90ec-a3989a1f4733.png)

**Comment by machaval** [comment]
Fixed! Thanks for reporting this

**Comment by machaval** [comment]
You need to use version 2.0.42

**Comment by iponisio** [comment]
Brilliant, thanks for looking into this @machaval !
